### PR TITLE
Strict-Transport-Security and extra headers

### PR DESCRIPTION
**Pull request by ubidzz**
Fixing the Strict-Transport-Security and add other Security headers.
This does work and tested with a clean install and all the correct headers are sent with non-SSL and SSL connections. 

Adding the Strict-Transport-Security, Referrer-Policy, X-Frame-Options, X-Content-Type-Options and X-XSS-Protection headers

you can test the headers at https://securityheaders.io

### CODE REVIEW

**Comment by Nirjonadda** [comment]
@ubidzz How we can doing this?

**Comment by Nirjonadda** [comment]
@ubidzz Still are not Security Report fixed. @fevangelou Looking for your next update version.

Ex: http://image.prntscr.com/image/3ac28d90f0c74c4d8627e93cf84610cf.png

```nginx
# /**
#  * @version    1.8.0
#  * @package    Engintron for cPanel/WHM
#  * @author     Fotis Evangelou
#  * @url        https://engintron.com
#  * @copyright  Copyright (c) 2010 - 2017 Nuevvo Webware P.C. All rights reserved.
#  * @license    GNU/GPL license: https://www.gnu.org/copyleft/gpl.html
#  */

# General Proxy Settings
proxy_pass          $scheme://$PROXY_DOMAIN_OR_IP:$PROXY_TO_PORT;
proxy_http_version  1.1;                # Always upgrade to HTTP/1.1
proxy_set_header    Accept-Encoding ""; # Optimize encoding
proxy_set_header    Connection "";      # Enable keepalives
proxy_set_header    Host $host;
proxy_set_header    Proxy "";
proxy_set_header    Referer $http_referer;
proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header    X-Forwarded-Host $host;
proxy_set_header    X-Forwarded-Port $server_port;
proxy_set_header    X-Forwarded-Proto $scheme;
proxy_set_header    X-Forwarded-Server $host;
proxy_set_header    X-Real-IP $remote_addr;
proxy_set_header    CF-Connecting-IP $http_cf_connecting_ip;
proxy_set_header    Cf-Visitor $http_cf_visitor;

# Buffers
proxy_buffers                 256 16k;
proxy_buffer_size             128k;
proxy_busy_buffers_size       256k;
proxy_temp_file_write_size    256k;

# Timeouts
proxy_connect_timeout         180s;
proxy_read_timeout            240s;
proxy_send_timeout            240s;

# Security Headers
add_header                    X-XSS-Protection "1; mode=block" always;
add_header                    X-Content-Type-Options "nosniff" always;
#if ($scheme = 'https') {
#   add_header                Strict-Transport-Security "max-age=86400; includeSubDomains" always;
#}

# Info
add_header                    X-Nginx-Cache-Status $upstream_cache_status;
add_header                    X-Server-Powered-By "Engintron";
```

**Comment by ubidzz** [comment]
replace this
```
# Security Headers
add_header                    X-XSS-Protection "1; mode=block" always;
add_header                    X-Content-Type-Options "nosniff" always;
#if ($scheme = 'https') {
#   add_header                Strict-Transport-Security "max-age=86400; includeSubDomains" always;
#}

# Info
add_header                    X-Nginx-Cache-Status $upstream_cache_status;
add_header                    X-Server-Powered-By "Engintron";
```
with this
```
if ($scheme = "https") {
    # Info
    add_header                    X-Nginx-Cache-Status $upstream_cache_status;
    add_header                    X-Server-Powered-By "Engintron";
    
    # Security Headers
    add_header                    Strict-Transport-Security "max-age=15768000; includeSubDomains" always;
    add_header                    Referrer-Policy "no-referrer-when-downgrade" always;
    add_header                    X-Frame-Options SAMEORIGIN;
    add_header                    X-Content-Type-Options "nosniff" always;
    add_header                    X-XSS-Protection "1; mode=block" always;
}

if ($scheme = "http"){
    # Info
    add_header                    X-Nginx-Cache-Status $upstream_cache_status;
    add_header                    X-Server-Powered-By "Engintron";
    
    # Security Headers
    add_header                    Referrer-Policy "no-referrer-when-downgrade" always;
    add_header                    X-Frame-Options SAMEORIGIN;
    add_header                    X-Content-Type-Options "nosniff" always;
    add_header                    X-XSS-Protection "1; mode=block" always;
}
```

**Comment by Nirjonadda** [comment]
@ubidzz Still are not fixed. EX: http://image.prntscr.com/image/d72c3b7f217a498589175e3d0bf644d1.png

````
# /**
#  * @version    1.8.0
#  * @package    Engintron for cPanel/WHM
#  * @author     Fotis Evangelou
#  * @url        https://engintron.com
#  * @copyright  Copyright (c) 2010 - 2017 Nuevvo Webware P.C. All rights reserved.
#  * @license    GNU/GPL license: https://www.gnu.org/copyleft/gpl.html
#  */

# General Proxy Settings
proxy_pass          $scheme://$PROXY_DOMAIN_OR_IP:$PROXY_TO_PORT;
proxy_http_version  1.1;                # Always upgrade to HTTP/1.1
proxy_set_header    Accept-Encoding ""; # Optimize encoding
proxy_set_header    Connection "";      # Enable keepalives
proxy_set_header    Host $host;
proxy_set_header    Proxy "";
proxy_set_header    Referer $http_referer;
proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header    X-Forwarded-Host $host;
proxy_set_header    X-Forwarded-Port $server_port;
proxy_set_header    X-Forwarded-Proto $scheme;
proxy_set_header    X-Forwarded-Server $host;
proxy_set_header    X-Real-IP $remote_addr;
proxy_set_header    CF-Connecting-IP $http_cf_connecting_ip;
proxy_set_header    Cf-Visitor $http_cf_visitor;

# Buffers
proxy_buffers                 256 16k;
proxy_buffer_size             128k;
proxy_busy_buffers_size       256k;
proxy_temp_file_write_size    256k;

# Timeouts
proxy_connect_timeout         180s;
proxy_read_timeout            240s;
proxy_send_timeout            240s;

if ($scheme = "https") {
    # Info
    add_header                    X-Nginx-Cache-Status $upstream_cache_status;
    add_header                    X-Server-Powered-By "Engintron";
    
    # Security Headers
    add_header                    Strict-Transport-Security "max-age=15768000; includeSubDomains" always;
    add_header                    Referrer-Policy "no-referrer-when-downgrade" always;
    add_header                    X-Frame-Options SAMEORIGIN;
    add_header                    X-Content-Type-Options "nosniff" always;
    add_header                    X-XSS-Protection "1; mode=block" always;
}

if ($scheme = "http"){
    # Info
    add_header                    X-Nginx-Cache-Status $upstream_cache_status;
    add_header                    X-Server-Powered-By "Engintron";
    
    # Security Headers
    add_header                    Referrer-Policy "no-referrer-when-downgrade" always;
    add_header                    X-Frame-Options SAMEORIGIN;
    add_header                    X-Content-Type-Options "nosniff" always;
    add_header                    X-XSS-Protection "1; mode=block" always;
}
````

**Comment by ubidzz** [comment]
though two are not added.

**Comment by Nirjonadda** [comment]
@ubidzz Two can be added?

**Comment by ubidzz** [comment]
No because the public-key-pin needs to use opensll to build the certs key for header and i don't know how.
The Content-Security-Policy will brake things on your website and just don't worry about though two headers.

**Comment by tux-tn** [comment]
You shouldn't force `X-Frame-Options` and `Strict-Transport-Security` globally for all your domains. It may lead to issues for some websites

**Comment by ubidzz** [comment]
I been running X-Frame-Options and Strict-Transport-Security and i have a lot of websites hosted on my server and they have no problems. The X-Frame-Options was added in Engintron because after i reinstalled it i found that and X-Content-Type-Options in the proxy_params_common file.

**Comment by tux-tn** [comment]
@ubidzz if it's working for you doesn't mean that the config won't lead to issue.

There are many different scenarios, for example:
1/ If a user want to have an iframe of a page from his domain.com on another domain2.com, your `X-Frame-Options` header will block it.
2/ If a user have a https domain and decides to return to http using a htaccess redirect, his site will break because of the HSTS header.

The only safe headers have already been implemented here #401

**Comment by ubidzz** [comment]
Well i guess i am lucky right now because i am not having any issues with the `X-Frame-Options`
I haven't tested the HSTS header fully but most of my users only want to use SSL on ever page so that their website is 100% SSL.

**Comment by fevangelou** [comment]
Read here why HSTS is not gonna happen anytime soon...

https://github.com/engintron/engintron/wiki/Changelog#feb-17th-2017---v180

**Pull request closed without merging**
