### PR TITLE
Update common_https.conf to meet PCI requirements

### PR DESCRIPTION
**Pull request by CarlosLopezES**
This version of TLS is being phased out. This warning won't break your padlock, however if you run an eCommerce site, PCI requirements state that TLSv1 must be disabled by June 30, 2018.

### CODE REVIEW

**Comment by fevangelou** [comment]
Mozilla SSL configurator's "intermediate" setup suggests otherwise: https://jmp.sh/McI1N8y

Anyway, it's pretty easy to adjust for your server specifically.

**Comment by CarlosLopezES** [comment]
Hi,

Sorry to update this, but i think that two years later, it's time to move forward on this, because, for one side, the Mozilla SSL configurator, on intermediate, now suggests only 1.2 and 1.3.

In the other hand, the SSL Tests like ssllabs.com, says that [it's outdated](https://blog.qualys.com/ssllabs/2018/11/19/grade-change-for-tls-1-0-and-tls-1-1-protocols) and will be capped to grade B.

King regards,

**Comment by fevangelou** [comment]
Noted for the next update. Thank you.

**Comment by CarlosLopezES** [comment]
Thank you! :)

**Pull request closed without merging**
