### PR TITLE
Add option to edit common_https.conf file

### PR DESCRIPTION
**Pull request by tux-tn**
I think users should be able to edit the common_https file

### CODE REVIEW

**Comment by ubidzz** [comment]
You can do this by adding the link and the page in to the /usr/local/cpanel/whostmgr/docroot/cgi/engintron.php page.

look for 
$allowed_files = array(
and add the page in the array like it is shown below
$allowed_files = array(
	'/etc/crontab',
	'/etc/nginx/nginx.conf',
	'/etc/nginx/proxy_params_common',
	'/etc/nginx/proxy_params_dynamic',
	'/etc/nginx/proxy_params_static',
	'/etc/nginx/custom_rules',
	'/etc/nginx/custom_rules.dist',
	'/etc/nginx/conf.d/default.conf',,
        '/etc/nginx/conf.d/common_https.conf',
	'/etc/my.cnf',
	'/usr/local/apache/conf/php.conf',
	'/usr/local/lib/php.ini'
);

I don't know the correct path and file because i use my own https script i made that is problem free and it use awk command to pull info from the httpd.conf file and not .

then scroll down to around line 515 and add the something like this
<li><a href="engintron.php?op=edit&f=/etc/nginx/conf.d/common_https.conf&s=nginx">Edit common_https.conf</a></li>

save and reload the plugin page in WHM and it will be in the list.

**Comment by tux-tn** [comment]
You are correct about `$allowed_files` array, i forgot to add the file so you were able to see it but not to edit. Fixed in the last commit.

PS: @ubidzz this is a pull request, not an open issue

**Comment by ubidzz** [comment]
I am glade i was able to help you fix your problem. I posted how to do it here so if anyone wants to add pages to the navbar links it tells them how.

**Comment by fevangelou** [comment]
Done n 1.8.2.

**Comment by tux-tn** [comment]
@fevangelou Thank you for your great work :+1:

**Pull request closed without merging**
