### PR TITLE
webmail.domain and bypass domains 

### PR DESCRIPTION
**Pull request by awsumco**
I have found that webmail.domain fails to work correctly with Horde and sometimes with SquirrelMail. Thus I have created cpanel.conf which does a proxy_pass directly to webmail ports. One small bug is that IPValid cookies will need to be set to off. Not great I know, but I am currently looking at how cPanel verifies the IP address. 

The 2nd part is bypass_domains, some of users did not want to be cached, so i enabled an option to bypass caching for a domain.

Thanks for considering my contribution

### CODE REVIEW

**Comment by 1uhost** [comment]
Great idea, thanks

**Comment by fevangelou** [comment]
@awsumco Your input is much appreciated, however the actual implementation is far simpler than the proposed solution you offer (in terms of Nginx's configuration). I will incorporate the exclusions for cPanel specific domains in v1.8.0.

**Comment by fevangelou** [comment]
@awsumco Bypassing caching for certain domains (or even URL paths) is also easier to maintain if it's moved inside "custom rules", so changes are not overwritten on subsequent Engintron updates.

**Comment by awsumco** [comment]
@fevangelou thanks for consider the pull request, I think you are correct the extra bypass_domains makes the configs a little convoluted.

**Comment by fevangelou** [comment]
See v1.7.3 I just released ;)

**Pull request closed without merging**
